import bcrypt from 'bcrypt'

export const users = [
    {
        name: "John Doe",
        email: "john.doe@example.com",
        password: bcrypt.hashSync("password1", 10),
        phoneNumber: "123-456-7890",
        address: "123 Main St, Exampleville, CA 12345"
    },
    {
        name: "name",
        email: "email",
        password: bcrypt.hashSync("password2", 10),
        phoneNumber: "098-765-4321",
        address: "456 Elm St, Exampletown, NY 67890"
    },
    {
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        password: bcrypt.hashSync("password3", 10),
        phoneNumber: "123-456-7891",
        address: "789 Oak St, Exampleton, CA 12345"
    },
    {
        name: "Bob Brown",
        email: "bob.brown@example.com",
        password: bcrypt.hashSync("password4", 10),
        phoneNumber: "123-456-7892",
        address: "123 Main St, Exampleville, CA 12345"
    },
    {
        name: "Charlie Davis",
        email: "charlie.davis@example.com",
        password: bcrypt.hashSync("password5", 10),
        phoneNumber: "123-456-7893",
        address: "456 Elm St, Exampletown, NY 67890"
    },
    {
        name: "David Green",
        email: "david.green@example.com",
        password: bcrypt.hashSync("password6", 10),
        phoneNumber: "123-456-7894",
        address: "789 Oak St, Exampleton, CA 12345"
    },
    {
        name: "Emily Hill",
        email: "emily.hill@example.com",
        password: bcrypt.hashSync("password7", 10),
        phoneNumber: "123-456-7895",
        address: "123 Main St, Exampleville, CA 12345"
    },
    {
        name: "Frank Lee",
        email: "frank.lee@example.com",
        password: bcrypt.hashSync("password8", 10),
        phoneNumber: "123-456-7896",
        address: "456 Elm St, Exampletown, NY 67890"
    },
    {
        name: "Grace Miller",
        email: "grace.miller@example.com",
        password: bcrypt.hashSync("password9", 10),
        phoneNumber: "123-456-7897",
        address: "789 Oak St, Exampleton, CA 12345"
    }
];

export const wines = [
    {
        brand: "Koor",
        name: "red sweet wine",
        type: "sweet",
        color: "red",
        img: "/images/koor_red_sweet_wine.png",
        rating: 5,
        stock: 5,
        article: "000000",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "55%",
        price: 9.52,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.nSuspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Armenia",
        name: "rose sweet wine",
        type: "sweet",
        color: "red",
        img: "/images/armenia_rose_sweet_wine.png",
        rating: 3,
        stock: 0,
        article: "000111",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "50%",
        price: 6.75,
        sales: 0,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Armenia",
        name: "Pomegranate",
        type: "dry",
        color: "red",
        img: "/images/armenia_pomegranate.png",
        rating: 2,
        stock: 5,
        article: "000520",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "52%",
        price: 8.59,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Zorah",
        name: "white dry wine",
        type: "dry",
        color: "white",
        img: "/images/zorah_white_dry_wine.png",
        rating: 3,
        stock: 25,
        article: "000201",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "58%",
        price: 6.75,
        sales: 0,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Tushpa",
        name: "white wine",
        type: "dry",
        color: "white",
        img: "/images/tushpa_white_wine.png",
        rating: 5,
        stock: 10,
        article: "000985",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "58%",
        price: 9.5,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Areni",
        name: "Qoto red wine",
        type: "sweet",
        color: "red",
        img: "/images/areni_qotot.png",
        rating: 5,
        stock: 30,
        article: "000745",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "58%",
        price: 8.59,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Karas",
        name: "Red wine",
        type: "dry",
        color: "red",
        img: "/images/karas_red_wine.png",
        rating: 3,
        stock: 0,
        article: "000582",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "55%",
        price: 8.59,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Tushpa",
        name: "White wine",
        type: "sweet",
        color: "wbite",
        img: "/images/tushpa_white_wine.png",
        rating: 2,
        stock: 10,
        article: "000312",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "52%",
        price: 9.5,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
    {
        brand: "Areni",
        name: "Qotot red wine",
        type: "sweet",
        color: "red",
        img: "/images/areni_qotot.png",
        rating: 4,
        stock: 0,
        article: "000753",
        country: "Armenia",
        region: "Areni",
        volume: "750ml",
        alcohol: "52%",
        price: 9.59,
        sales: 10,
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.Suspendisse a venenatis ex. Praesent ut diam sit amet ipsum hendrerit lacinia nec ut turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed sollicitudin lacus sed quam laoreet, et elementum diam varius. Etiam eu placerat libero.",
    },
];

